config/routes.rb
Rails.application.routes.draw do
  get 'guest_orders/update'
  get 'orders/update'
  get 'guest_order_items/create'
  get 'guest_order_items/update'
  get 'guest_order_items/destroy'
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
                                       :registrations => "users/registrations",
                                       :sessions => "users/sessions" }
  devise_scope :user do
    get '/guest_identify' => 'users/registrations#identify', :as => :identify
    post '/quick_registration' => 'users/registrations#quick_registration', :as => :quick_registration
  end

  match '/users/settings', to: 'users#settings', via: :get
  match '/users/update', to: 'users#update', via: :patch
  match '/users/update_password', to: 'users#update_password', via: :patch
  match '/users/destroy', to: 'users#destroy', via: :delete
  match '/users/billing_country_change', to: 'users#billing_country_change', via: :get
  match '/users/shipping_country_change', to: 'users#shipping_country_change', via: :get

  match '/billing_addresses/update/:id', to: 'billing_addresses#update', via: :patch
  match '/billing_addresses/create', to: 'billing_addresses#create', via: :post

  match '/shipping_addresses/update/:id', to: 'shipping_addresses#update', via: :patch
  match '/shipping_addresses/create', to: 'shipping_addresses#create', via: :post

  match '/checkout_addresses', to: 'checkout_addresses#index', via: :get
  match '/checkout_addresses/order_billing_country_change', to: 'checkout_addresses#billing_country_change', via: :get
  match '/checkout_addresses/order_shipping_country_change', to: 'checkout_addresses#shipping_country_change', via: :get

  match '/order_addresses/update/:id', to: 'order_addresses#update', via: :patch
  match '/order_addresses/create', to: 'order_addresses#create', via: :post

  match '/checkout_deliveries', to: 'checkout_deliveries#index', via: :get
  match '/checkout_deliveries/update', to: 'checkout_deliveries#update', via: :post

  match '/checkout_payments', to: 'checkout_payments#index', via: :get

  match '/payment_cards/update/:id', to: 'payment_cards#update', via: :patch
  match '/payment_cards/create', to: 'payment_cards#create', via: :post

  match '/checkout_confirms', to: 'checkout_confirms#index', via: :get
  match '/checkout_confirms/edit_address', to: 'checkout_confirms#edit_address', via: :get
  match '/checkout_confirms/edit_delivery', to: 'checkout_confirms#edit_delivery', via: :get
  match '/checkout_confirms/edit_payment', to: 'checkout_confirms#edit_payment', via: :get

  match '/orders/place_order', to: 'orders#place_order', via: :get

  match '/checkout_completes/:id', to: 'checkout_completes#index', via: :get

  match '/orders', to: 'orders#index', via: :get
  match '/order/:id', to: 'orders#show', via: :get

  resources :books, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end

  root 'home#index'
  match '/admin/reviews/approve/:id', to: 'admin/reviews#approve', via: :get
  match '/admin/reviews/reject/:id', to: 'admin/reviews#reject', via: :get

  resource :cart, only: [:show]
  
  resources :order_items, only: [:create, :update, :destroy]
  resources :guest_order_items, only: [:create, :update, :destroy]
  
  match '/order_items/decrement/:id', to: 'order_items#decrement', via: :patch
  match '/order_items/increment/:id', to: 'order_items#increment', via: :patch

  match '/guest_order_items/decrement/:id', to: 'guest_order_items#decrement', via: :patch
  match '/guest_order_items/increment/:id', to: 'guest_order_items#increment', via: :patch

  match '/orders/:id', to: 'orders#update', via: :patch
  match '/guest_orders/:id', to: 'guest_orders#update', via: :patch

end

app/controllers/home_controller.rb
class HomeController < ApplicationController  
  def index
    @last_added_books = Book.last(3)
    @best_sellers = @best_sellers = Book.find_by_sql("SELECT * FROM 
      (SELECT *, ROW_NUMBER() OVER (PARTITION BY category_id order by order_counter DESC) AS Row_ID FROM books) AS A
      WHERE Row_ID < 2 ORDER BY category_id")
    @order_item = current_order.order_items.new if current_user
    @order_item = current_order.guest_order_items.new if !current_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def limit_description(description)
    "#{description[0, 180]}..."
  end

  def authors(authors)
    authors.map { |d| d }.join(", ").html_safe
  end
end

app/views/home/index.html.haml
/ - provide(:title, "Home")

#slider.carousel.slide{'data-ride': "carousel"}
  %ol.carousel-indicators
    - @last_added_books.each_with_index do |book, index|
      %li{class: (index == 0 ? 'active' : ''), 'data-target': "#slider", 'data-slide-to': index.to_s}
  .carousel-inner{role: "listbox"}
    - @last_added_books.each_with_index do |book, index|
      .item{class: (index == 0 ? 'active' : ''), href: "#slider", 'data-slide': "next"}
        .row
          .col-sm-5.img-container
            .general-img-wrap
              %img.img-shadow.general-thumbnail-img{'src': book.covers[0].url(:medium), alt: book.title}
          .col-sm-7
            .mb-60
              %h2.slide-titile #{book.title}
              %p.lead.description #{limit_description(book.short_description)}
              %p.lead.small #{authors(book.authors)}
              .general-align.stop-propagation
                = form_for @order_item, remote: true do |f|
                  = f.hidden_field :book_id, value: book.id
                  = f.hidden_field :quantity, value: "1"
                  = button_tag( :class => "btn btn-primary carousel-buy-link") do
                    %span.btn-title= t('home.buy_now')
.container
  .jumbotron.text-center.mb-0
    %h2.h1= t('home.welcome_msg')
    .mb-res-50.message
      %p= t('home.info_msg')
    = link_to t('home.get_started'), books_path(custom_sort: "title ASC"), class: "btn btn-default button-link", id: "get-started"
.mb-35.best-sellers-container
  %h3 Best Sellers
  .row.best-seller-item
    - @best_sellers.each do |book|
      = render 'books/book', book: book, order_item: @order_item