config/routes.rb
Rails.application.routes.draw do
  get 'guest_orders/update'
  get 'orders/update'
  get 'guest_order_items/create'
  get 'guest_order_items/update'
  get 'guest_order_items/destroy'
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
                                       :registrations => "users/registrations",
                                       :sessions => "users/sessions" }
  devise_scope :user do
    get '/guest_identify' => 'users/registrations#identify', :as => :identify
    post '/quick_registration' => 'users/registrations#quick_registration', :as => :quick_registration
  end

  match '/users/settings', to: 'users#settings', via: :get
  match '/users/update', to: 'users#update', via: :patch
  match '/users/update_password', to: 'users#update_password', via: :patch
  match '/users/destroy', to: 'users#destroy', via: :delete
  match '/users/billing_country_change', to: 'users#billing_country_change', via: :get
  match '/users/shipping_country_change', to: 'users#shipping_country_change', via: :get

  match '/billing_addresses/update/:id', to: 'billing_addresses#update', via: :patch
  match '/billing_addresses/create', to: 'billing_addresses#create', via: :post

  match '/shipping_addresses/update/:id', to: 'shipping_addresses#update', via: :patch
  match '/shipping_addresses/create', to: 'shipping_addresses#create', via: :post

  match '/checkout_addresses', to: 'checkout_addresses#index', via: :get
  match '/checkout_addresses/order_billing_country_change', to: 'checkout_addresses#billing_country_change', via: :get
  match '/checkout_addresses/order_shipping_country_change', to: 'checkout_addresses#shipping_country_change', via: :get

  match '/order_addresses/update/:id', to: 'order_addresses#update', via: :patch
  match '/order_addresses/create', to: 'order_addresses#create', via: :post

  match '/checkout_deliveries', to: 'checkout_deliveries#index', via: :get
  match '/checkout_deliveries/update', to: 'checkout_deliveries#update', via: :post

  match '/checkout_payments', to: 'checkout_payments#index', via: :get

  match '/payment_cards/update/:id', to: 'payment_cards#update', via: :patch
  match '/payment_cards/create', to: 'payment_cards#create', via: :post

  match '/checkout_confirms', to: 'checkout_confirms#index', via: :get
  match '/checkout_confirms/edit_address', to: 'checkout_confirms#edit_address', via: :get
  match '/checkout_confirms/edit_delivery', to: 'checkout_confirms#edit_delivery', via: :get
  match '/checkout_confirms/edit_payment', to: 'checkout_confirms#edit_payment', via: :get

  match '/orders/place_order', to: 'orders#place_order', via: :get

  match '/checkout_completes/:id', to: 'checkout_completes#index', via: :get

  match '/orders', to: 'orders#index', via: :get
  match '/order/:id', to: 'orders#show', via: :get

  resources :books, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end

  root 'home#index'
  match '/admin/reviews/approve/:id', to: 'admin/reviews#approve', via: :get
  match '/admin/reviews/reject/:id', to: 'admin/reviews#reject', via: :get

  resource :cart, only: [:show]
  
  resources :order_items, only: [:create, :update, :destroy]
  resources :guest_order_items, only: [:create, :update, :destroy]
  
  match '/order_items/decrement/:id', to: 'order_items#decrement', via: :patch
  match '/order_items/increment/:id', to: 'order_items#increment', via: :patch

  match '/guest_order_items/decrement/:id', to: 'guest_order_items#decrement', via: :patch
  match '/guest_order_items/increment/:id', to: 'guest_order_items#increment', via: :patch

  match '/orders/:id', to: 'orders#update', via: :patch
  match '/guest_orders/:id', to: 'guest_orders#update', via: :patch

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items if current_order.is_a? Order
    @order_items = current_order.guest_order_items if current_order.is_a? GuestOrder
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def round_price(price)
    price.round(2)
  end

  def count_discount(subtotal, discount)
    "€#{(subtotal * discount / 100).round(2)}"
  end

  def get_cart_url(order)
    order.is_a?(Order) ? "/orders/#{order.id}" : "/guest_orders/#{order.id}"
  end
end

app/views/carts/_narrow_cart_row.html.haml
.general-cart-item.divider-lg-bottom
  = button_to "&times;".html_safe, order_item, method: :delete, remote: true, class: "close general-cart-close"
  .general-img-wrap-table
    %img.cart-img-shadow{'src': book.covers[0].url(:thumb), alt: book.title}
  %p.title #{book.title}
  %table.table
    %tr
      %td
        %span.in-grey-600 Price
      %td
        %span.font-16.in-gold-500 €#{order_item.unit_price}
    %tr
      %td.vertical-middle
        %span.in-grey-600 Quantity
      %td
        .input-group.general-position
          = link_to "-", get_url(order_item, 'decrement'), method: :patch, remote: true, class: "quantity-link"
          %input.form-control.quantity-input{type: "text", value: order_item.quantity.to_i, readonly: true, name: "quantity"}
          = link_to "+", get_url(order_item, 'increment'), method: :patch, remote: true, class: "quantity-link"
    %tr
      %td
        %span.in-grey-600 SubTotal
      %td
        %span.font-16.in-gold-500 €#{order_item.total_price}

app/views/carts/_shopping_cart.html.haml
- if !@order_item.nil? && @order_item.errors.any?
  .alert.alert-danger
    %ul
      - @order_item.errors.full_messages.each do |msg|
        %li ${msg}
- if @order_items.size == 0
  %p.text-center.no-items= t('cart_page.no_items')
- else
  .visible-xs
    - @order_items.each do |order_item|
      = render 'carts/narrow_cart_row', book: order_item.book, order_item: order_item
  .hidden-xs
    %table.table.table-hover.cart-container
      %tr.no-hover
        %th.col-pic.pl-0
          %span.in-grey-600= t('cart_page.product')
        %th.col-title
        %th.col-price
          %span.in-grey-600= t('cart_page.price')
        %th.col-quantity
          %span.in-grey-600= t('cart_page.qty')
        %th.col-total
          %span.in-grey-600= t('cart_page.subtotal')
        %th.col-close
      - @order_items.each do |order_item|
        = render 'carts/wide_cart_row', book: order_item.book, order_item: order_item
  .general-order-wrap
    .row
      = form_for current_order, url: get_cart_url(current_order), method: :patch, remote: true do |f| 
        .col-sm-4
          .input-group.general-input-group
            %label.input-label= t('cart_page.coupon_label')
            = f.text_field :discount, class: 'form-control mb-30', placeholder: "Enter Your Coupon Code", value: "", disabled: !current_user, id: "discount-input"
            %div
              = button_tag( class: "btn btn-primary mb-15 res-block", disabled: !current_user) do
                %span.btn-title= t('cart_page.update_cart')
      .col-sm-8
        .res-mr-200.text-center.general-text-right
          %p.in-gold-500.font-18= t('cart_page.order_summary')
          %table.general-summary-table.general-summary-table-right.general-text-right
            %tr
              %td
                %p.font-16= t('cart_page.subtotal_summary')
              %td
                %p.font-16.subtotal €#{round_price(current_order.subtotal)}
            %tr
              %td
                %p.font-16= t('cart_page.coupon')
              %td
                %p.font-16.discount= count_discount(current_order.subtotal, current_order.discount)
            %tr
              %td
                %strong.font-18= t('cart_page.order_total')
              %td
                %strong.font-18.total €#{round_price(current_order.total)}
          - if !current_user
            = link_to t('cart_page.checkout'), identify_path, class: "btn btn-default mb-20 visible-xs-inline-block checkout-btn"
          - else
            = link_to t('cart_page.checkout'), "#", class: "btn btn-default mb-20 visible-xs-inline-block checkout-btn"
  - if !current_user
    = link_to t('cart_page.checkout'), identify_path, class: "btn btn-default mb-20 hidden-xs center-block checkout-btn"
  - else
    = link_to t('cart_page.checkout'), checkout_addresses_path, class: "btn btn-default mb-20 hidden-xs center-block checkout-btn"






  

app/views/carts/_wide_cart_row.html.haml
%tr
  %td
    .general-img-wrap-table
      %img.cart-img-shadow.pull-left{'src': book.covers[0].url(:thumb), alt: book.title}
  %td
    %p.title #{book.title}
  %td
    %span.font-16.in-gold-500 €#{order_item.unit_price}
  %td
    .input-group.general-position{data: order_item.id, book: order_item.book.id, user: current_user ? 'user' : 'guest'}
      = link_to "-", get_url(order_item, 'decrement'), method: :patch, remote: true, class: "quantity-link"
      %input.form-control.quantity-input{type: "text", value: order_item.quantity.to_i, readonly: true, name: "quantity"}
      = link_to "+", get_url(order_item, 'increment'), method: :patch, remote: true, class: "quantity-link"
  %td
    %span.font-16.in-gold-500 €#{order_item.total_price}
  %td
    = button_to "&times;".html_safe, order_item, method: :delete, remote: true, class: "close general-cart-close"

app/views/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('cart_page.cart_title')
  .shopping-cart
    = render 'shopping_cart'